project:
  type: website

lang: es 

website:
  title: "Arturo Sanjuán"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cursos/index.qmd
        text: Cursos

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true




