project:
  type: website

lang: es 

language:
  title-block-author-single: "Autor"
  title-block-author-plural: "Autores"

website:
  title: "Arturo Sanjuán"
  site-url: "https://arturosanjuan.xyz"
  favicon: "favicon.png"
  page-navigation: true
  comments:
    giscus:
      repo: "asanjuanc/arturosanjuan-sitio"
      repo-id: "R_kgDOTzuHrw"
      category: "Comentarios"
      category-id: "DIC_kwDOTzuHr84DD_eD"
      mapping: pathname
      reactions-enabled: true
      loading: lazy
      input-position: "top"
      theme: preferred_color_scheme
      language: "es"
  navbar:
    left:
      - href: cursos/index.qmd
        text: Cursos
  sidebar:
    - id: odes
      title: "Ecuaciones Diferenciales"
      style: docked
      tools:
        - icon: rss
          href: cursos/odes/index.xml
          text: "RSS — Ecuaciones Diferenciales"
      contents:
        -- cursos/odes/index.qmd
        - cursos/odes/introduccion/index.qmd
        - cursos/odes/familiasortogonales/index.qmd
        - cursos/odes/modelacion/index.qmd
        - cursos/odes/polares/index.qmd
        - cursos/odes/taller-1/index.qmd
    - id: numerico
      title: "Análisis Numérico"
      style: docked
      tools:
        - icon: rss
          href: cursos/numerico/index.xml
          text: "RSS — Análisis Numérico"
      contents:
        - cursos/numerico/index.qmd
        - cursos/numerico/introduccion/index.qmd
        - cursos/numerico/condicionamiento/index.qmd
        - cursos/numerico/estabilidad/index.qmd
        - cursos/numerico/taller-1/index.qmd
        - cursos/numerico/matrices/index.qmd
    - id: probabilidad
      title: "Probabilidad"
      style: docked
      tools:
        - icon: rss
          href: cursos/probabilidad/index.xml
          text: "RSS — Probabilidad"
      contents:
        - cursos/probabilidad/index.qmd
        - cursos/probabilidad/introduccion/index.qmd
        - cursos/probabilidad/calculoprobabilidades/index.qmd
        - cursos/probabilidad/condicional/index.qmd
        - cursos/probabilidad/taller-1/index.qmd
        - cursos/probabilidad/vaintro/index.qmd
        - cursos/probabilidad/vadiscretas/index.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true